# Generated by Django 5.2.7 on 2025-10-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
